version: '3'
services:
  fastcgi:
    build: 
      context: ./phpfpm
    volumes:
      - ./frontend/MainApp/:/usr/share/nginx/html/MainApp/
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend/MainApp/:/usr/share/nginx/html/MainApp/
    ports: 
      - 3082:8080
    depends_on:
      - fastcgi
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend/files/:/usr/share/nginx/html/files/
    depends_on:
      - fastcgi     


  #  environment:
  #     PMA_HOST: localhost
  # backend:
  #   build: 
  #     context: ./backend
  #   volumes:
  #     - ./backend/files/:/var/www/html/files/
  #   ports: 
  #     - 3082:80    
  #   hostname: backend.internal
  # money-transfer:
  #   build: 
  #     context: ./money-transfer
  #   volumes:
  #     - ./money-transfer/api/:/var/www/html/api/
  #   hostname: money-transfer.internal
  # refer-a-friend:
  #   build: 
  #     context: ./refer-a-friend
  #   volumes:
  #     - ./refer-a-friend/app3/:/var/www/html/app3/
  #   ports: 
  #     - 3083:80
  #   hostname: refer-a-friend.internal
  # nginx:
  #   build: 
  #     context: ./nginx-reverse-proxy
  #   ports: 
  #     - 3080:80
  #   depends_on:
  #     - frontend
  #     - backend
  # mortgage-fastcgi:
  #   build: 
  #     context: ./mortgage-calculator
  #     dockerfile: phpfpm.Dockerfile
  #   volumes:
  #     - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/
  #   hostname: fastcgi
  # mortgage-nginx:
  #   build: 
  #     context: ./mortgage-calculator
  #     dockerfile: nginx.Dockerfile      
  #   volumes:
  #     - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/      
  #   ports: 
  #    - 5080:8080
  #   hostname: mortgage-nginx.internal
  #   depends_on:
  #     - mortgage-fastcgi     